# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginSyncQGISGeoServer
                                 A QGIS plugin
 El plugin personalizado "SyncQGISGeoServer" facilita la sincronización bidireccional de datos entre QGIS y GeoServer, permitiendo exportar capas desde QGIS a GeoServer y visualizar capas desde GeoServer en QGIS mediante servicios WFS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-27
        copyright            : (C) 2024 by Innovacion DPVER
        email                : innovaciondpver@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PluginSyncQGISGeoServer class from file PluginSyncQGISGeoServer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sync_qgis_geoserver import PluginSyncQGISGeoServer
    return PluginSyncQGISGeoServer(iface)
